PR to merge new features from genepattern repo to ampliconSuite repo
AmpliconSuite/AmpliconSuiteAggregator pull request #20
Opened 2023-06-08 20:03 UTC by edwin5588

- features including
    - POST functionality #16 
    - exclusion list for issue #13

2023-06-29 17:31 UTC, jluebeck requested changes
Hi @edwin5588, thanks much for these features. I am requesting a few additional updates and fixes to the things you've implemented, then we can merge it.

Thanks!
Jens

2023-06-29 17:31 UTC, jluebeck commented on gpunit/inputs.zip
Did you mean to include these testing samples in the commit?

2023-06-29 17:31 UTC, jluebeck commented on Dockerfile
Hi @edwin5588, the following dependencies are not needed:
Cython, biopython, reportlab, pyfaidx, pysam, cnvkit, Flask, numpy, mosek, future

URL for AC should probably be updated to https://github.com/AmpliconSuite/AmpliconClassifier.

Also looks like intervaltree is listed twice?

2023-06-29 17:31 UTC, jluebeck commented on src/ASA_POST.py
I see the following filepath hardcoded here: 
/Users/edwinhuang/Downloads/test_POST_from_gpBeta.tar.gz - should this be changed?

2023-06-29 17:31 UTC, jluebeck commented on src/ASA_POST.py
@edwin5588 Project members is also set to your email address. Should this be an argument instead?

2023-06-29 17:31 UTC, jluebeck commented on src/AmpliconSuiteAggregatorFunctions.py
I think the ecxlusion list '`.gz`' pattern is probably too generic. The only time it should be filtered for .gz is if it is a `.fq.gz` or `.fastq.gz`.

2023-06-29 17:31 UTC, jluebeck commented on src/AmpliconSuiteAggregator.py
for the `--run_classifier` arg, argparse arugments can be set to python's 'True' by adding `action=store_true` to the `add_argument` call. This sets it as a boolean flag instead of a flag with argument. The argument's value will be `None` if `--run_classifier` is not given, so you can directly do `if args.run_classifier` instead. This is much preferred over having the argument set to a semi-arbitrary string like "Yes" and checking equality to that string.

2023-06-29 17:31 UTC, jluebeck commented on src/AmpliconSuiteAggregatorFunctions.py
Line 40: see commentabout argparse `action=store_true`.

2023-06-29 17:31 UTC, jluebeck commented on src/AmpliconSuiteAggregator.py
If args.run_classifier is set, then args.ref must be set too. There should be some logic to enforce that after the args are parsed.

2023-06-29 17:31 UTC, jluebeck commented on src/AmpliconSuiteAggregator.py
It looks like args.server is not used or given to post_package and the URL will always be the dev server as a result. Maybe this is the desired behavior for now?

2023-06-29 17:31 UTC, jluebeck commented on src/AmpliconSuiteAggregator.py
@edwin5588 Can you copy over the argparse line for args.ref directly from AmpliconClassifier? This way the reference genome the user types is required to be one we recognize.

`parser.add_argument("--ref", help="Reference genome name used for alignment, one of hg19, GRCh37, GRCh38, GRCh38_viral, or mm10", choices=["hg19", "GRCh37", "GRCh38", "GRCh38_viral", "mm10"])`

2023-06-29 17:31 UTC, jluebeck commented on src/AmpliconSuiteAggregatorFunctions.py
> +            os.system(f"wget -q -P $AA_DATA_REPO https://datasets.genepattern.org/data/module_support_files/AmpliconArchitect/{self.ref}_indexed_md5sum.tar.gz")
Should be the non-indexed md5sum

2023-06-29 17:31 UTC, jluebeck commented on src/AmpliconSuiteAggregatorFunctions.py
> +                for i in CLASSIFIER_FILES:
A faster way to check this is to first separate the CLASSIFIER_FILES from the classifier directories (i.e. make a separate variabel for 'CLASSIFIER_DIRECTORIES', then instead of '`for i'`, check
```
if any([fp.endswith(x) for x in CLASSIFIER_FILES]):
   # remove the file
```

A similar logic applies for the directory removal on line 192.

2023-06-29 17:48 UTC, edwin5588 commented on src/AmpliconSuiteAggregator.py
I did it this way because from GP module interface, the user will be given a dropdown menu with 2 choices: "Yes" "No" as strings to be passed into the module when run.

2023-06-29 17:49 UTC, edwin5588 commented on src/AmpliconSuiteAggregator.py
will do

2023-06-29 17:51 UTC, edwin5588 commented on src/AmpliconSuiteAggregatorFunctions.py
> +            os.system(f"wget -q -P $AA_DATA_REPO https://datasets.genepattern.org/data/module_support_files/AmpliconArchitect/{self.ref}_indexed_md5sum.tar.gz")
Which download link are you referring to?

2023-06-29 17:52 UTC, edwin5588 commented on src/ASA_POST.py
This part is just for testing only. I'll comment it out.

2023-06-29 17:54 UTC, edwin5588 commented on src/AmpliconSuiteAggregator.py
the argument isn't used yet because the API functionality still needs to be pushed and tested on the production server.

2023-06-29 18:45 UTC, jluebeck commented on src/AmpliconSuiteAggregatorFunctions.py
> +            os.system(f"wget -q -P $AA_DATA_REPO https://datasets.genepattern.org/data/module_support_files/AmpliconArchitect/{self.ref}_indexed_md5sum.tar.gz")
Line 204: `{self.ref}_indexed_md5sum.tar.gz` should be `{self.ref}_md5sum.tar.gz`

2023-06-29 19:12 UTC, jluebeck commented on src/AmpliconSuiteAggregator.py
Does GP module interface support checkbox buttons? If so that would be a good way to give a binary value.

2023-06-29 19:25 UTC, edwin5588 commented on src/AmpliconSuiteAggregator.py
Would it make sense to just have the user make an input for --ref? The parameter description could say: "Specify reference genome if you want to re-run amplicon classifier."

Or would it make sense to parse the metadata files to try to find the reference genomes used?

2023-07-04 18:07 UTC, jluebeck approved these changes

2023-07-04 19:11 UTC, merged